brew cask install adoptopenjdk8
brew cask install brave-browser
brew cask install dnscrypt
brew cask install google-cloud-sdk
brew cask install handbrake
brew cask install inkscape
brew cask install libreoffice
brew cask install pycharm
brew cask install pycharm-ce
brew cask install sublime-text
brew cask install tunnelblick
brew cask install turbo-boost-switcher
brew cask install vlc